### PR TITLE
Create src directory before writing the file

### PR DESCRIPTION
**Pull request by nopeless**

### CODE REVIEW

**Comment by nopeless** [comment]
```ts
// Ensure directories exist
{
  const e = (...p: string[]) => {
    if (!fs.existsSync(path.resolve(repoDirectory, ...p))) {
      fs.mkdirSync(path.resolve(repoDirectory, ...p));
    }
  };

  e("src");
  e("src", themesDirectory);
}
```

Something like this would be more appropriate actually

**Comment by Unthrottled** [comment]
Just as a fyi you could 

```
fs.mkdirSync(path.resolve(repoDirectory, ...directories), {recursive: true})
```

Which will recursively create the parents if needed.

**Comment by Unthrottled** [comment]
Thanks!

**Comment by nopeless** [comment]
> Just as a fyi you could
> 
> ```
> fs.mkdirSync(path.resolve(repoDirectory, ...directories), {recursive: true})
> ```
> 
> Which will recursively create the parents if needed.

Didn't know that, thanks

**Pull request merged**
